#print(type("22"))
#print(type(22.3))
#print(type(0))
#print(type(True))
#print(type(False))
#print(type(str(22)))
#int()
#float()
print(bool(-1))

#nome = input("Informe su nome:")
#print(type(int(nome)))